version: '3'
services:
  db:
    build:
      context: ./mysql
    volumes:
      - .:/go/src/avito-task/sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: links
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: golang_db
    ports:
      - "3307:3307"
    tty: true
  app:
    build:
      context: .
    volumes:
      - .:/go/src/avito-task
    container_name: golang_app
    ports:
      - "9000:9000"
    tty: true
    depends_on:
      - db